server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}
        - id: pet-service
          uri: lb://pet-service
          predicates:
            - Path=/pet/**
          filters:
            - RewritePath=/pet/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  version: '@springdoc.version@'
  swagger-ui:
    use-root-path: true
    urls:
      - name: customer
        url: /v3/api-docs/customer
      - name: pet
        url: /v3/api-docs/pet